#ifndef DATA_HEADERS
#define DATA_HEADERS

#define MEMORY_BOOT_DRIVE_ADDRESS (CONVENTIONAL_MEM_START + 0x00) // 1 byte
#define MEMORY_IO_EXT_SUPERBLOCK_ADDRESS (CONVENTIONAL_MEM_START + 0x100) // 1024 bytes

#define MEMORY_BOOT_STAGE15_ADDRESS (CONVENTIONAL_MEM2_START + 0x00) // 512 bytes


#endif