#ifndef EXT_HEADERS
#define EXT_HEADERS

#define EXT_MAGIC_NUMBER 0xEF53

#define EXT_INODES_COUNT_OFFSET 0x00
#define EXT_BLOCKS_COUNT_OFFSET 0x04
#define EXT_RBLOCKS_COUNT_OFFSET 0x08
#define EXT_FREE_BLOCKS_COUNT_OFFSET 0x0C
#define EXT_FREE_INODES_COUNT_OFFSET 0x10
#define EXT_FIRST_DATA_BLOCK_OFFSET 0x14
#define EXT_LOG_BLOCK_SIZE_OFFSET 0x18
#define EXT_BLOCKS_PER_GROUP_OFFSET 0x20
#define EXT_INODES_PER_GROUP_OFFSET 0x28
#define EXT_MAGIC_OFFSET 0x38

#endif