#ifndef BOOT_HEADERS
#define BOOT_HEADERS

#define BOOT_IO_SECTOR_SIZE 512
#define BOOT_IO_EXT4_SUPERBLOCK_OFFSET 1024
#define BOOT_IO_EXT4_SUPERBLOCK_SIZE 1024
#define BOOT_IO_EXT4_SUPERBLOCK_START_SECTOR (BOOT_IO_EXT4_SUPERBLOCK_OFFSET / BOOT_IO_SECTOR_SIZE)
#define BOOT_IO_EXT4_SUPERBLOCK_SECTOR_COUNT (BOOT_IO_EXT4_SUPERBLOCK_SIZE / BOOT_IO_SECTOR_SIZE)

#endif